@extends('layouts.app')
@section('title','Dashboard')
@section('content')
<div class="max-w-7xl mx-auto">
<div class="mb-5"><h2 class="page-heading">Good day, {{ $user->name }}!</h2><p class="page-subheading">{{ now()->format('l, F j, Y') }} · {{ $user->isOwner()?'Owner':($user->isStoreManager()?'Store Manager':'Inventory Staff') }}</p></div>
@if($user->isInventoryStaff())
 <a href="{{ route('daily-counts.index') }}" class="dashboard-primary {{ $todayCount?'is-complete':'' }}"><div><span class="dashboard-eyebrow">TODAY'S CLOSING INVENTORY</span><div class="text-2xl font-extrabold mt-1">{{ $todayCount?'Submitted':'Daily Count Not Yet Submitted' }}</div><p class="mt-1 opacity-90">{{ $todayCount ? 'Submitted '.$todayCount->submitted_at?->format('g:i A').' · tap to view' : 'Tap here to start the end-of-day physical count' }}</p></div><span class="text-3xl">→</span></a>
@else
 <a href="{{ route('daily-counts.index') }}" class="dashboard-primary {{ $todayCount?'is-complete':'' }}"><div><span class="dashboard-eyebrow">TODAY'S DAILY INVENTORY</span><div class="text-2xl font-extrabold mt-1">{{ $todayCount?'Submitted':'Not Yet Submitted' }}</div><p class="mt-1 opacity-90">{{ $todayCount ? ($todayCount->user->name ?? 'Staff').' · '.$todayCount->submitted_at?->format('g:i A').' · read only' : 'Waiting for Inventory Staff closing count' }}</p></div><span class="text-3xl">→</span></a>
@endif
<section class="grid grid-cols-2 lg:grid-cols-4 gap-3 my-5"><a href="{{ route('inventory.index') }}" class="ui-card stat-card tap"><div class="text-sm font-semibold text-slate-500">Inventory Items</div><div class="text-3xl font-extrabold">{{ $totalItems }}</div></a><a href="{{ route('stock.low') }}" class="ui-card stat-card tap"><div class="text-sm font-semibold text-slate-500">Low Stock</div><div class="text-3xl font-extrabold {{ $lowStockCount?'text-amber-600':'text-green-600' }}">{{ $lowStockCount }}</div></a><a href="{{ route('stock.low') }}" class="ui-card stat-card tap"><div class="text-sm font-semibold text-slate-500">Out of Stock</div><div class="text-3xl font-extrabold {{ $outOfStockCount?'text-red-600':'' }}">{{ $outOfStockCount }}</div></a>@if(!$user->isOwner())<a href="{{ route('purchases.index') }}" class="ui-card stat-card tap"><div class="text-sm font-semibold text-slate-500">{{ $user->isStoreManager()?'Pending Approval':'Purchase Requests' }}</div><div class="text-3xl font-extrabold">{{ $pendingPurchases }}</div></a>@else<a href="{{ route('reports.index') }}" class="ui-card stat-card tap"><div class="text-sm font-semibold text-slate-500">Reports</div><div class="text-xl font-extrabold text-green-700">View & Print →</div></a>@endif</section>
@if($user->isStoreManager())
 <div class="grid md:grid-cols-2 gap-4 mb-5"><a href="{{ route('purchases.index') }}" class="ui-card p-5 tap"><div class="text-sm font-bold text-amber-700">NEEDS YOUR ATTENTION</div><div class="text-2xl font-bold mt-1">{{ $pendingPurchases }} purchase request{{ $pendingPurchases==1?'':'s' }} pending</div><p class="text-slate-500 mt-1">Approve or reject directly from Purchases.</p></a><a href="{{ route('reports.index') }}" class="ui-card p-5 tap"><div class="text-sm font-bold text-green-700">OPERATIONS</div><div class="text-2xl font-bold mt-1">View Reports</div><p class="text-slate-500 mt-1">Daily inventory, movements, low stock and purchases.</p></a></div>
@endif
@if($user->isOwner())
 <div class="grid md:grid-cols-2 gap-4 mb-5"><a href="{{ route('reports.index') }}" class="ui-card p-5 tap"><div class="text-sm font-bold text-green-700">OWNER REPORTING</div><div class="text-2xl font-bold mt-1">Generate / Print Reports</div><p class="text-slate-500 mt-1">Choose a report, set the period and print or save it as PDF.</p></a><a href="{{ route('employees.index') }}" class="ui-card p-5 tap"><div class="text-sm font-bold text-green-700">ADMINISTRATION</div><div class="text-2xl font-bold mt-1">Manage Employees</div><p class="text-slate-500 mt-1">Accounts, roles and access status.</p></a></div>
@endif
<div class="grid lg:grid-cols-2 gap-5"><div class="ui-card overflow-hidden"><div class="ui-card-header flex justify-between"><div><h3 class="font-bold text-lg">Inventory Attention</h3><p class="text-sm text-slate-500">Items at or below reorder level</p></div><a href="{{ route('stock.low') }}" class="font-bold text-green-700">View all</a></div><div class="p-4">@forelse($lowStockItems as $item)<div class="flex justify-between gap-3 py-3 border-b last:border-0"><div><strong>{{ $item->name }}</strong><div class="text-xs text-slate-500">{{ $item->category }}</div></div><span class="status-pill {{ $item->stock_qty<=0?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700' }}">{{ $item->stock_qty }} {{ $item->unit }}</span></div>@empty<div class="empty-state">No items need attention.</div>@endforelse</div></div><div class="ui-card overflow-hidden"><div class="ui-card-header"><h3 class="font-bold text-lg">Recent Inventory Activity</h3><p class="text-sm text-slate-500">Latest recorded stock movements</p></div><div class="p-4">@forelse($recentActivity as $tx)<div class="flex justify-between gap-3 py-3 border-b last:border-0"><div><strong>{{ $tx->item->name }}</strong><div class="text-xs text-slate-500">{{ $tx->user->name ?? 'User' }} · {{ $tx->reference ?: ucfirst($tx->type) }}</div></div><strong class="{{ $tx->type==='in'?'text-green-600':'text-orange-600' }}">{{ $tx->type==='in'?'+':'−' }}{{ $tx->quantity }}</strong></div>@empty<div class="empty-state">No activity yet.</div>@endforelse</div></div></div>
</div>
@endsection